# fromsource-policy.yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: nginx-process-restriction
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  action: Block
  process:
    matchPaths:
    - path: /bin/bash
    - path: /bin/sh
  file:
    matchPaths:
    - path: /etc/shadow
  severity: 7
  message: "Block shell access and sensitive files"
