apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-certificate
  namespace: wisecow
spec:
  secretName: wisecow-tls
  issuerRef:
    name: wisecow-issuer
    kind: ClusterIssuer
  commonName: wisecow.local
  dnsNames:
    - wisecow.local
